### ISSUE TITLE
Specific folder

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [santileortiz/Iconoscope#10]
Hello i'm creating some personal icons that i put in my `$HOME/Design` folder.

and I would like to visualize them but iconoscope dont detect them.. so i had to copy them to `/usr/share/icons/hicolor/`, `/usr/share/icons/` or similar folder

is it possible to add an option that will allow us to choose a specific folder?

**Comment by santileortiz** [comment]
I've been meaning to implement this since the beginning. The problem is your folder will most likely not have the `index.theme` file that the application uses to locate icons and their properties.

What I want to do is make reasonable guesses about icons in a folder without this file, but I need more information about the directory structure users have. For example I would like it to work in the `data` directory that looks like:

```
data
├── 128
│   └── iconoscope.svg
├── 32
│   └── iconoscope.svg
├── 48
│   └── iconoscope.svg
├── 64
│   └── iconoscope.svg
├── base_icon.svg
├── screenshot.png
└── ...
```

In this case I would like sizes to be guessed from the folder name, but I don't want `base_icon.svg` or ` screenshot.png` to show as icons.

What is the folder structure of your directory `$HOME/Design`? what do you expect the application to guess from it? Before I implement this, I would like to have several use cases so I can decide on some sane defaults.

**Comment by mIcHyAmRaNe** [comment]
as we are on elementary os which recommends [ 6 types of sizes](https://elementary.io/fr/docs/human-interface-guidelines#size)

i made my design folder like in `/usr/share/icons/elementary/apps/$size`: 

```
design
    └ apps  // to distinguish that these are application icons
        ├── 128
        │   └── icon.svg
        ├── 16
        │   └── icon.svg
        ├── 24
        │   └── icon.svg
        ├── 32
        │   └── icon.svg
        ├── 48
        │   └── icon.svg
        └── 64
             └── icon.svg
```

but i think that there are people who create it as in `/usr/share/icons/hicolor/$size/apps`
and here `$size` folders are 128x128 instead of 128

personally what i want is that as you said iconoscope detect icon size from folder name (whether it is `$size` or `$sizex$size`) and can show the icon from `$size/icon.svg`  or `$size/folder/icon.svg`
